language: csharp
solution: Unosquare.Labs.LiteLib.sln
notifications:
  slack: unolabs:cbusXPH6pBwZ35rVDzi4k4ve
dotnet: 2.0.0
install:
  - dotnet restore
  - sudo apt-get install sqlite
script:
  - dotnet test ./test/Unosquare.Labs.LiteLib.Tests/Unosquare.Labs.LiteLib.Tests.csproj -f netcoreapp2.0
