language: csharp
solution: Unosquare.Labs.LiteLib.sln
dotnet: 2.1.300
notifications:
  slack: unolabs:cbusXPH6pBwZ35rVDzi4k4ve
install:
  - dotnet restore
  - sudo apt-get install sqlite
script:
  - dotnet test ./test/Unosquare.Labs.LiteLib.Tests/Unosquare.Labs.LiteLib.Tests.csproj
