version: '1.7.{build}'
image: 
- Visual Studio 2017
- Ubuntu
build:
  project: Unosquare.Labs.LiteLib.sln
configuration:
- Release
notifications:
- provider: Slack
  auth_token:
    secure: Q+xg4/yU5OR9BVF14cw4yZ+3qlhMeYDsAhUQyOIszmF1mHvq44tIvQpWByBJCd/cgUIZk3SwBpk4hh1MrkQIk6rnaOZ2LNBTev4zrq36oXk=
  channel: '#builds'
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  CODACY_PROJECT_TOKEN:
    secure: mTPE0JGPljPlUENlBuSc9/9081IM66qDQescxx0ueMk+66+qPxnqgmdfLLW/13hY
  COVERALLS_REPO_TOKEN:  
       secure: dVpAqavd3jP7LMW+oswLBPfihwiGDZUtWDQWJadMO1Gj61SYegxNsGTZOT2BYN6+
  op_build_user: "Geo Perez"
  op_build_user_email: "geovanni.perez@gmail.com"
  access_token:
       secure: HzWdswNyfQbQ0vLk9IQyO+Ei9mxoPYp9rvv6HPhtC9J/Fm7EHRzyV953pbPRXI9I
init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
before_build:
- ps: |
        if(-Not $env:APPVEYOR_PULL_REQUEST_TITLE -And $isWindows)
        {
            git checkout $env:APPVEYOR_REPO_BRANCH -q
            cinst docfx -y --no-progress
        }
- dotnet restore -v Minimal
- dotnet tool install -g coveralls.net
- ps: Start-FileDownload 'https://github.com/codacy/codacy-coverage-reporter/releases/download/4.0.3/codacy-coverage-reporter-4.0.3-assembly.jar'
build_script:
- cmd: msbuild /p:Configuration=Release /verbosity:quiet
test_script:
- dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:Exclude=[NUnit3.TestAdapter]* test/Unosquare.Labs.LiteLib.Tests/Unosquare.Labs.LiteLib.Tests.csproj -c Release -f netcoreapp2.1
- ps: |
        if(-Not $env:APPVEYOR_PULL_REQUEST_TITLE -And $isWindows)
        {
            csmacnz.coveralls --lcov -i test\Unosquare.Labs.LiteLib.Tests\coverage.info --serviceName appveyor --jobId %APPVEYOR_BUILD_NUMBER% --useRelativePaths
        }
- cmd: java -jar codacy-coverage-reporter-4.0.3-assembly.jar report -l CSHarp -r test\Unosquare.Labs.LiteLib.Tests\coverage.xml
after_build:
- ps: |
        if(-Not $env:APPVEYOR_PULL_REQUEST_TITLE -And $isWindows)
        {
            docfx docfx.json
            git config --global credential.helper store
            Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
            git config --global core.autocrlf false 
            git config --global user.email $env:op_build_user_email
            git config --global user.name $env:op_build_user

            git clone https://github.com/unosquare/litelib.git -b gh-pages origin_site -q
            git clone -b documentation https://github.com/unosquare/best-practices.git -q
            docfx docfx.json --logLevel Error
            Copy-Item origin_site/.git _site -recurse
            CD _site
            Copy-Item README.html index.html -force
            git add -A 2>&1
            git commit -m "Documentation update" -q
            git push origin gh-pages -q
            CD ..
        }
